config/routes.rb
Rails.application.routes.draw do
  resources :portfolio_items
  get 'dashboard', to: 'dashboard#index'

  resources :site_infos
  devise_for :users
  root 'home#index'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/portfolio_item.rb
class PortfolioItem < ApplicationRecord
  validates :name, :description, :date_completed, presence: true

  mount_uploader :image, PortfolioItemImageUploader

end

app/models/site_info.rb
class SiteInfo < ApplicationRecord
  validates :brand_name, :welcome_message, :page_title, :call_to_action, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :get_brand_name

  def get_brand_name
    @brand_name = SiteInfo.last.brand_name
  end
  
end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController
  before_action :authenticate_user!
  def index
@site_info = SiteInfo.last
@portfolio_item = PortfolioItem.all
  end

  def show

  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @site_info = SiteInfo.last
  end
end

app/controllers/portfolio_items_controller.rb
class PortfolioItemsController < ApplicationController
  before_action :set_portfolio_item, only: [:show, :edit, :update, :destroy]

  # GET /portfolio_items
  # GET /portfolio_items.json
  def index
    @portfolio_items = PortfolioItem.all
  end

  # GET /portfolio_items/1
  # GET /portfolio_items/1.json
  def show
  end

  # GET /portfolio_items/new
  def new
    @portfolio_item = PortfolioItem.new
  end

  # GET /portfolio_items/1/edit
  def edit
  end

  # POST /portfolio_items
  # POST /portfolio_items.json
  def create
    @portfolio_item = PortfolioItem.new(portfolio_item_params)

    respond_to do |format|
      if @portfolio_item.save
        format.html { redirect_to @portfolio_item, notice: 'Portfolio item was successfully created.' }
        format.json { render :show, status: :created, location: @portfolio_item }
      else
        format.html { render :new }
        format.json { render json: @portfolio_item.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /portfolio_items/1
  # PATCH/PUT /portfolio_items/1.json
  def update
    respond_to do |format|
      if @portfolio_item.update(portfolio_item_params)
        format.html { redirect_to @portfolio_item, notice: 'Portfolio item was successfully updated.' }
        format.json { render :show, status: :ok, location: @portfolio_item }
      else
        format.html { render :edit }
        format.json { render json: @portfolio_item.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /portfolio_items/1
  # DELETE /portfolio_items/1.json
  def destroy
    @portfolio_item.destroy
    respond_to do |format|
      format.html { redirect_to portfolio_items_url, notice: 'Portfolio item was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_portfolio_item
      @portfolio_item = PortfolioItem.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def portfolio_item_params
      params.require(:portfolio_item).permit(:name, :description, :image, :date_completed)
    end
end

app/controllers/site_infos_controller.rb
class SiteInfosController < ApplicationController
  before_action :authenticate_user!
  before_action :set_site_info, only: [:show, :edit, :update, :destroy]

  # GET /site_infos
  # GET /site_infos.json
  def index
    @site_infos = SiteInfo.all
  end

  # GET /site_infos/1
  # GET /site_infos/1.json
  def show
  end

  # GET /site_infos/new
  def new
    @site_info = SiteInfo.new
  end

  # GET /site_infos/1/edit
  def edit
  end

  # POST /site_infos
  # POST /site_infos.json
  def create
    @site_info = SiteInfo.new(site_info_params)

    respond_to do |format|
      if @site_info.save
        format.html { redirect_to @site_info, notice: 'Site info was successfully created.' }
        format.json { render :show, status: :created, location: @site_info }
      else
        format.html { render :new }
        format.json { render json: @site_info.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /site_infos/1
  # PATCH/PUT /site_infos/1.json
  def update
    respond_to do |format|
      if @site_info.update(site_info_params)
        format.html { redirect_to @site_info, notice: 'Site info was successfully updated.' }
        format.json { render :show, status: :ok, location: @site_info }
      else
        format.html { render :edit }
        format.json { render json: @site_info.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /site_infos/1
  # DELETE /site_infos/1.json
  def destroy
    @site_info.destroy
    respond_to do |format|
      format.html { redirect_to site_infos_url, notice: 'Site info was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_site_info
      @site_info = SiteInfo.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def site_info_params
      params.require(:site_info).permit(:brand_name, :welcome_message, :page_title, :call_to_action)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/dashboard_helper.rb
module DashboardHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/portfolio_items_helper.rb
module PortfolioItemsHelper
end

app/helpers/site_infos_helper.rb
module SiteInfosHelper
end

app/views/dashboard/index.html.erb
<%= render 'layouts/navbar' %>
<div class="card">
  <div class="card-body">
    <h1>Edit site homepage</h1>

    <%= render 'site_infos/form', site_info: @site_info %>

  </div>

</div>

 <!-- render 'portfolio_items/index' -->

app/views/home/_Header.html.erb
<!-- Home/Header -->
<header class="masthead masthead-overlay fullscreen">
  <div class="container container-size">


    <div class="intro-text ">

<div class="md-col-3">
        <img class="rounded-circle img-fluid" src="<%= asset_path 'li2.jpg'%>" width="200px" height="200px"  alt="Picture of Annabelle"/>
</div> <br>
      <div class="intro-lead-in">
        <%= @site_info.welcome_message %>
      </div>
      <div class="intro-heading text-uppercase">
        <%= @site_info.page_title %>
      </div>
      <a class="btn btn-primary btn-xl text-uppercase js-scroll-trigger" href="#contact">
        <%= @site_info.call_to_action %>
      </a>
    </div>
  </div>
</header>

app/views/home/_about.html.erb
<!-- About -->
<section id="about">
  <div class="container">
    <div class="row">
      <div class="col-lg-12 text-center">
        <h2 class="section-heading text-uppercase">My Journey</h2>
        <h3 class="section-subheading text-muted">My journey so far, how I got to where I am. </h3>
      </div>
    </div>
    <div class="row">
      <div class="col-lg-12">
        <ul class="timeline">
          <li>
            <div class="timeline-image">
              <img class="rounded-circle img-fluid" src= "<%= asset_path 'about/1.jpg'%>" alt="thumbnail 1">
            </div>
            <div class="timeline-panel">
              <div class="timeline-heading">
                <h4>2013</h4>
                <h4 class="subheading">Graduated high school. </h4>
              </div>
              <div class="timeline-body">
                <p class="text-muted">Completed the Higher School Certificate from a government selective school achieving in the top 10% of the state. </p>
              </div>
            </div>
          </li>
          <li class="timeline-inverted">
            <div class="timeline-image">
              <img class="rounded-circle img-fluid" src="<%= asset_path 'about/2.jpg'%>" alt="">
            </div>
            <div class="timeline-panel">
              <div class="timeline-heading">
                <h4>January 2018</h4>
                <h4 class="subheading">Graduated University</h4>
              </div>
              <div class="timeline-body">
                <p class="text-muted">Completed Bachelors degree in Science majoring in Psychology. </p>
              </div>
            </div>
          </li>
          <li>
            <div class="timeline-image">
              <img class="rounded-circle img-fluid" src="<%= asset_path 'about/3.jpg' %>" alt="">
            </div>
            <div class="timeline-panel">
              <div class="timeline-heading">
                <h4>February 2018</h4>
                <h4 class="subheading">Started Coding Boot Camp</h4>
              </div>
              <div class="timeline-body">
                <p class="text-muted">Began a website and application development boot camp at <a href="https://www.digitalintelligence.institute/">Digital Intelligence Institute</a> from which this portfolio website application came to be created. </p>
              </div>
            </div>

          </li>
          <li class="timeline-inverted">
            <div class="timeline-image">
              <img class="rounded-circle img-fluid" src="<%= asset_path 'about/4.jpg'%>" alt="">
            </div>
            <div class="timeline-panel">
              <div class="timeline-heading">
                <h4>Currently...</h4>
                <h4 class="subheading">Recruited by Digital Inteligence!</h4>
              </div>
              <div class="timeline-body">
                <p class="text-muted">Social media brand and content strategist and web developer intern. Continuously learning and embracing the tech environment around me. </p>
              </div>
            </div>
          </li>
          <li class="timeline-inverted">
            <div class="timeline-image">
              <h4>Be Part
                <br>Of My
                <br>Story!</h4>
            </div>
          </li>
        </ul>
      </div>
    </div>
  </div>
</section>

app/views/home/_portfoliogrid.html.erb
<!-- Portfolio Grid -->
<section class="bg-light2" id="portfolio">
  <div class="container">
    <div class="row">
      <div class="col-lg-12 text-center">
        <h2 class="section-heading text-uppercase">Portfolio</h2>
        <h3 class="section-subheading  white-text">This is where my future portolio items will be showcased.</h3>
      </div>
    </div>
    <div class="row">
      <div class="col-md-4 col-sm-6 portfolio-item">
        <a class="portfolio-link" data-toggle="modal" href="#portfolioModal1">
          <div class="portfolio-hover">
            <div class="portfolio-hover-content">
              <i class="fa fa-plus fa-3x"></i>
            </div>
          </div>
          <img class="img-fluid" src=" <%= asset_path 'portfolio/01-thumbnail.jpg' %>" alt="">
        </a>
        <div class="portfolio-caption">
          <h4>Threads</h4>
          <p class="text-muted">Illustration</p>
        </div>
      </div>
      <div class="col-md-4 col-sm-6 portfolio-item">
        <a class="portfolio-link" data-toggle="modal" href="#portfolioModal2">
          <div class="portfolio-hover">
            <div class="portfolio-hover-content">
              <i class="fa fa-plus fa-3x"></i>
            </div>
          </div>
          <img class="img-fluid" src="<%= asset_path 'portfolio/02-thumbnail.jpg' %>" alt="">
        </a>
        <div class="portfolio-caption">
          <h4>Explore</h4>
          <p class="text-muted">Graphic Design</p>
        </div>
      </div>
      <div class="col-md-4 col-sm-6 portfolio-item">
        <a class="portfolio-link" data-toggle="modal" href="#portfolioModal3">
          <div class="portfolio-hover">
            <div class="portfolio-hover-content">
              <i class="fa fa-plus fa-3x"></i>
            </div>
          </div>
          <img class="img-fluid" src="<%= asset_path 'portfolio/03-thumbnail.jpg' %>" alt="">
        </a>
        <div class="portfolio-caption">
          <h4>Finish</h4>
          <p class="text-muted">Identity</p>
        </div>
      </div>
      <div class="col-md-4 col-sm-6 portfolio-item">
        <a class="portfolio-link" data-toggle="modal" href="#portfolioModal4">
          <div class="portfolio-hover">
            <div class="portfolio-hover-content">
              <i class="fa fa-plus fa-3x"></i>
            </div>
          </div>
          <img class="img-fluid" src="<%= asset_path 'portfolio/04-thumbnail.jpg' %>" alt="">
        </a>
        <div class="portfolio-caption">
          <h4>Lines</h4>
          <p class="text-muted">Branding</p>
        </div>
      </div>
      <div class="col-md-4 col-sm-6 portfolio-item">
        <a class="portfolio-link" data-toggle="modal" href="#portfolioModal5">
          <div class="portfolio-hover">
            <div class="portfolio-hover-content">
              <i class="fa fa-plus fa-3x"></i>
            </div>
          </div>
          <img class="img-fluid" src="<%= asset_path 'portfolio/05-thumbnail.jpg' %>" alt="">
        </a>
        <div class="portfolio-caption">
          <h4>Southwest</h4>
          <p class="text-muted">Website Design</p>
        </div>
      </div>
      <div class="col-md-4 col-sm-6 portfolio-item">
        <a class="portfolio-link" data-toggle="modal" href="#portfolioModal6">
          <div class="portfolio-hover">
            <div class="portfolio-hover-content">
              <i class="fa fa-plus fa-3x"></i>
            </div>
          </div>
          <img class="img-fluid" src="<%= asset_path 'portfolio/06-thumbnail.jpg' %>" alt="">
        </a>
        <div class="portfolio-caption">
          <h4>Window</h4>
          <p class="text-muted">Photography</p>
        </div>
      </div>
    </div>
  </div>
</section>

app/views/home/_services.html.erb
<!-- Services -->
<!-- <section id="services">
  <div class="container">
    <div class="row">
      <div class="col-lg-12 text-center">
        <h2 class="section-heading text-uppercase">Services</h2>
        <h3 class="section-subheading text-muted">Lorem ipsum dolor sit amet consectetur.</h3>
      </div>
    </div>
    <div class="row text-center"> -->
      <!-- <div class="col-md-4">
        <span class="fa-stack fa-4x">
          <i class="fa fa-circle fa-stack-2x text-primary"></i>
          <i class="fa fa-shopping-cart fa-stack-1x fa-inverse"></i>
        </span>
        <h4 class="service-heading">E-Commerce</h4>
        <p class="text-muted">Lorem ipsum dolor sit amet, consectetur adipisicing elit. Minima maxime quam architecto quo inventore harum ex magni, dicta impedit.</p>
      </div>
      <div class="col-md-4">
        <span class="fa-stack fa-4x">
          <i class="fa fa-circle fa-stack-2x text-primary"></i>
          <i class="fa fa-laptop fa-stack-1x fa-inverse"></i>
        </span> -->
        <!-- <h4 class="service-heading">Responsive Design</h4>
        <p class="text-muted">Lorem ipsum dolor sit amet, consectetur adipisicing elit. Minima maxime quam architecto quo inventore harum ex magni, dicta impedit.</p>
      </div>
      <div class="col-md-4">
        <span class="fa-stack fa-4x">
          <i class="fa fa-circle fa-stack-2x text-primary"></i>
          <i class="fa fa-lock fa-stack-1x fa-inverse"></i>
        </span>
        <h4 class="service-heading">Web Security</h4>
        <p class="text-muted">Lorem ipsum dolor sit amet, consectetur adipisicing elit. Minima maxime quam architecto quo inventore harum ex magni, dicta impedit.</p>
      </div>
    </div>
  </div>
</section> -->

app/views/home/index.html.erb
<%= render 'home/Header' %>


<%= render 'layouts/experience' %>


<%= render 'home/portfoliogrid' %>


<%= render 'home/about' %>



<%= render 'layouts/teamaboutme' %>


<%= render 'layouts/contact' %>


<%= render 'layouts/modals' %>

app/views/layouts/_contact.html.erb
<!-- Contact -->
<section id="contact">
  <div class="container">
    <div class="row">
      <div class="col-lg-12 text-center">
        <h2 class="section-heading text-uppercase">Contact Me</h2>
        <h3 class="section-subheading text-muted">I would love to hear from you!</h3>
      </div>
    </div>
    <div class="row">
      <div class="col-lg-12">
        <form id="contactForm" name="sentMessage" novalidate>
          <div class="row">
            <div class="col-md-6">
              <div class="form-group">
                <input class="form-control" id="name" type="text" placeholder="Your Name *" required data-validation-required-message="Please enter your name.">
                <p class="help-block text-danger"></p>
              </div>
              <div class="form-group">
                <input class="form-control" id="email" type="email" placeholder="Your Email *" required data-validation-required-message="Please enter your email address.">
                <p class="help-block text-danger"></p>
              </div>
              <div class="form-group">
                <input class="form-control" id="phone" type="tel" placeholder="Your Phone *" required data-validation-required-message="Please enter your phone number.">
                <p class="help-block text-danger"></p>
              </div>
            </div>
            <div class="col-md-6">
              <div class="form-group">
                <textarea class="form-control" id="message" placeholder="Your Message *" required data-validation-required-message="Please enter a message."></textarea>
                <p class="help-block text-danger"></p>
              </div>
            </div>
            <div class="clearfix"></div>
            <div class="col-lg-12 text-center">
              <div id="success"></div>
              <button id="sendMessageButton" class="btn btn-primary btn-xl text-uppercase" type="submit">Send Message</button>
            </div>
          </div>
        </form>
      </div>
    </div>
  </div>
</section>

app/views/layouts/_experience.html.erb
<!-- Start Exprience Area -->
<section class="section-gap exprience-area">
  <div class="container">
    <div class="row">
      <div class="col-lg-3 col-md-6 mb-sm-20">
        <!-- MArgin bottom- MB SMALL SCREEN SM-20 pixels  -->
        <div class="exprience-thumb" ></div>
      </div>
      <div class="col-lg-3 col-md-6">
        <div class="exprience-thumb" ></div>
      </div>
      <div class="col-lg-6">
        <div class="exprience-content">
          <h2>Welcome to Annabelle's Digital Portfolio <br> </h2>
          <h6 class="sub-exprience-title">This is a showcase of what I've learnt at <a href="https://www.digitalintelligence.institute/">Digital Intelligence Institute</a>  and my journey into web development.</h6>
          <p>Upon completing an undergraduate degree in psychology and in search for work, the possibilities of what career to apply into seemed endless and confusing. This made me question what direction I was going in, and ultimately which direction the world and society are moving towards. Hence the idea of coding came into the picture.  </p>
          <!-- <a href="#" class="primary-btn">View Details</a> -->
        </div>
      </div>
    </div>
  </div>
</section>
<!-- End Exprience Area -->

app/views/layouts/_footer.html.erb
<!-- Footer -->
    <footer>
      <div class="container">
        <div class="row">
          <div class="col-md-4">
            <span class="copyright">Copyright &copy; Annabelle Kho 2018</span>
          </div>
          <div class="col-md-4">
            <ul class="list-inline social-buttons">
              <li class="list-inline-item">
                <a href="#">
                  <i class="fa fa-twitter"></i>
                </a>
              </li>
              <li class="list-inline-item">
                <a href="#">
                  <i class="fa fa-facebook"></i>
                </a>
              </li>
              <li class="list-inline-item">
                <a href="https://www.linkedin.com/in/annabelle-kho-417153b6/" target="_blank">
                  <i class="fa fa-linkedin"></i>
                </a>
              </li>
            </ul>
          </div>
          <div class="col-md-4">
            <ul class="list-inline quicklinks">
              <li class="list-inline-item">
                <a href="#">Privacy Policy</a>
              </li>
              <li class="list-inline-item">
                <a href="#">Terms of Use</a>
              </li>
            </ul>
          </div>
        </div>
      </div>
    </footer>

app/views/layouts/_navbar.html.erb
<!-- Navigation -->
<nav class="navbar navbar-expand-lg navbar-dark fixed-top" id="mainNav">
  <div class="container">
    <a class="navbar-brand js-scroll-trigger" href="#page-top">Welcome</a>
    <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
      Menu
      <i class="fa fa-bars"></i>
    </button>
    <div class="collapse navbar-collapse" id="navbarResponsive">
      <ul class="navbar-nav text-uppercase ml-auto">

        <!-- <li class="nav-item">
          <a class="nav-link js-scroll-trigger" href="#portfolio">Portfolio</a>
        </li> -->
        <li class="nav-item">
          <a class="nav-link js-scroll-trigger" href="#">Intro</a>
          <!-- Intro/experience -->
        </li>
        <li class="nav-item ">
    <a class="nav-link  js-scroll-trigger" href="#portfolio" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
      Portfolio
    </a>

        <li class="nav-item">
          <a class="nav-link js-scroll-trigger" href="#about">My Journey</a>
        </li>
        <li class="nav-item">
          <a class="nav-link js-scroll-trigger" href="#team">About Me</a>
        </li>
        <li class="nav-item">
          <a class="nav-link js-scroll-trigger" href="#contact">Contact</a>
        </li>
      </ul>
    </div>
  </div>
</nav>

app/views/layouts/dashboard.html.erb
<!DOCTYPE html>
<html>
  <head>

    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>Portfolio</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <link href="https://fonts.googleapis.com/css?family=Montserrat:400,700" rel="stylesheet" type="text/css">
    <link href='https://fonts.googleapis.com/css?family=Kaushan+Script' rel='stylesheet' type='text/css'>
    <link href='https://fonts.googleapis.com/css?family=Droid+Serif:400,700,400italic,700italic' rel='stylesheet' type='text/css'>
    <link href='https://fonts.googleapis.com/css?family=Roboto+Slab:400,100,300,700' rel='stylesheet' type='text/css'>




  </head>

  <body id="page-top">
    <%= render 'layouts/navbar' %>
    <div class="mt-5 pt-5 container">
      <div class="row">
        <div class="col-md-3">
          <h4 class="text-muted">Sidebar menu</h4>
          <p> <%= link_to 'Dashboard', dashboard_path %> </p>
        </div>
        <div class="col-md-9">
          <%= yield %>
        </div>

      </div>

    </div>



      <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

  </body>
</html>

app/views/portfolio_items/_form.html.erb
<%= simple_form_for(@portfolio_item) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :name, label: false, placeholder: 'Title of project' %>
    <%= f.input :description, label: false, placeholder: 'Description of project', input_html: { rows:5 }  %>
    <%= f.input :image, label: false, placeholder: 'Upload Image'%>
    <%= f.input :date_completed, label: false, placeholder: 'Date project completed' %>

  </div>

  <div class="form-actions">
    <%= f.submit "Create new portfolio", class:'btn btn-outline-success btn-sm' %>
  </div>
<% end %>

app/views/portfolio_items/edit.html.erb
<h1>Editing Portfolio Item</h1>

<%= render 'form', portfolio_item: @portfolio_item %>

<%= link_to 'Show', @portfolio_item %> |
<%= link_to 'Back', portfolio_items_path %>

app/views/portfolio_items/index.html.erb
<p id="notice"><%= notice %></p>
<div class="container mt-5 ">



<h1>Portfolio Items</h1>

<table class="table">
  <thead>
    <tr>
      <th>Image</th>
      <th>Name</th>
      <th>Description</th>
      <th>Date completed</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @portfolio_items.each do |portfolio_item| %>
      <tr>
        <td><%= portfolio_item.image %></td>
        <td><%= portfolio_item.name %></td>
        <td><%= truncate (portfolio_item.description) %></td>
        <td><%= portfolio_item.date_completed %></td>
        <td><%= link_to 'Show', portfolio_item %></td>
        <td><%= link_to 'Edit', edit_portfolio_item_path(portfolio_item) %></td>
        <td><%= link_to 'Destroy', portfolio_item, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>


<%= link_to 'New Portfolio Item', new_portfolio_item_path %>
</div>

app/views/portfolio_items/new.html.erb
<div class="container mt-5 ">


<h1>Add New Portfolio Item</h1>

<%= render 'form', portfolio_item: @portfolio_item %>

<%= link_to 'Back', portfolio_items_path %>
</div>

app/views/portfolio_items/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @portfolio_item.name %>
</p>

<p>
  <strong>Description:</strong>
  <%= @portfolio_item.description %>
</p>

<p>
  <strong>Image:</strong>
  <%= @portfolio_item.image %>
</p>

<p>
  <strong>Date completed:</strong>
  <%= @portfolio_item.date_completed %>
</p>

<%= link_to 'Edit', edit_portfolio_item_path(@portfolio_item) %> |
<%= link_to 'Back', portfolio_items_path %>

app/views/site_infos/edit.html.erb
<h1>Editing Site Info</h1>

<%= render 'form', site_info: @site_info %>

<%= link_to 'Show', @site_info %> |
<%= link_to 'Back', site_infos_path %>

app/views/site_infos/index.html.erb
<p id="notice"><%= notice %></p>


<div class="container mt-5">
  <div class="row mt-3">
    <div class="card card-body ">
      <h1>Site Infos</h1>

      <table>
        <thead>
          <tr>
            <th>Brand name</th>
            <th>Welcome message</th>
            <th>Page title</th>
            <th>Call to action</th>
            <th colspan="3"></th>
          </tr>
        </thead>

        <tbody>
          <% @site_infos.each do |site_info| %>
            <tr>
              <td><%= site_info.brand_name %></td>
              <td><%= site_info.welcome_message %></td>
              <td><%= site_info.page_title %></td>
              <td><%= site_info.call_to_action %></td>
              <td><%= link_to 'Show', site_info %></td>
              <td><%= link_to 'Edit', edit_site_info_path(site_info) %></td>
              <td><%= link_to 'Destroy', site_info, method: :delete, data: { confirm: 'Are you sure?' } %></td>
            </tr>
          <% end %>
        </tbody>
      </table>

      <br>

      <%= link_to 'New Site Info', new_site_info_path %>

    </div>

  </div>

</div>

app/views/site_infos/new.html.erb
<h1>New Site Info</h1>

<%= render 'form', site_info: @site_info %>

<%= link_to 'Back', site_infos_path %>

app/views/site_infos/show.html.erb
<p id="notice"><%= notice %></p>

<div class="container mt-5">
  <div class="row">
    <div class="card card-body mt-3">
      <p>
        <strong>Brand name:</strong>
        <%= @site_info.brand_name %>
      </p>

      <p>
        <strong>Welcome message:</strong>
        <%= @site_info.welcome_message %>
      </p>

      <p>
        <strong>Page title:</strong>
        <%= @site_info.page_title %>
      </p>

      <p>
        <strong>Call to action:</strong>
        <%= @site_info.call_to_action %>
      </p>

      <%= link_to 'Edit', edit_site_info_path(@site_info) %> |
      <%= link_to 'Back', site_infos_path %>
    </div>

  </div>

</div>